"""Descriptor-based column and expression primitives.

This is the real (if minimal) implementation of the pattern described in
the README: a metaclass owns both `__slots__` generation and the
descriptor protocol, so `Column` can behave as a live instance accessor
*and* return a query expression at class-level access.
"""


class Condition:
    """A single `column OP value` predicate, generated by comparing a
    ColumnExpr against a Python value at class scope (e.g. `User.id > 100`)."""

    __slots__ = ("column_name", "op", "value")

    def __init__(self, column_name, op, value):
        self.column_name = column_name
        self.op = op
        self.value = value

    def to_sql(self, placeholder="?"):
        return f"{self.column_name} {self.op} {placeholder}", self.value


class ColumnExpr:
    """Returned by `Column.__get__` when accessed on the class rather than
    an instance. Comparisons build a `Condition` instead of a bool."""

    __slots__ = ("model", "name", "py_type")

    def __init__(self, model, name, py_type):
        self.model = model
        self.name = name
        self.py_type = py_type

    def __eq__(self, other):
        return Condition(self.name, "=", other)

    def __ne__(self, other):
        return Condition(self.name, "!=", other)

    def __gt__(self, other):
        return Condition(self.name, ">", other)

    def __ge__(self, other):
        return Condition(self.name, ">=", other)

    def __lt__(self, other):
        return Condition(self.name, "<", other)

    def __le__(self, other):
        return Condition(self.name, "<=", other)

    def __hash__(self):
        return hash((self.model, self.name))

    def __repr__(self):
        return f"<ColumnExpr {self.model.__name__}.{self.name}>"


class Column:
    def __init__(self, py_type: type):
        self.py_type = py_type
        self.name = None
        self._storage_name = None

    def __set_name__(self, owner, name):
        self.name = name
        self._storage_name = f"_{name}"

    def __get__(self, obj, owner=None):
        if obj is None:
            return ColumnExpr(owner, self.name, self.py_type)
        return getattr(obj, self._storage_name)

    def __set__(self, obj, value):
        setattr(obj, self._storage_name, value)


class ModelMeta(type):
    """Owns slot generation instead of delegating to @dataclass, since a
    Column descriptor and a same-named slot can't coexist (see README)."""

    def __new__(mcs, name, bases, namespace):
        columns = {
            key: value for key, value in namespace.items() if isinstance(value, Column)
        }
        namespace["__slots__"] = tuple(f"_{col_name}" for col_name in columns)
        namespace["__columns__"] = columns
        return super().__new__(mcs, name, bases, namespace)

    def __getattr__(cls, name):
        # Compile the per-model orjson hook on first use, then cache it as a
        # real class attribute so later lookups never reach __getattr__.
        if name == "__json_default__":
            from .compile import compile_json_default

            fn = compile_json_default(cls)
            setattr(cls, name, fn)
            return fn
        raise AttributeError(name)


def hydrate(model_cls, row):
    """Build an instance from a positional row (tuple/Record) without going
    through __init__ or per-field keyword dispatch."""
    obj = object.__new__(model_cls)
    for column, value in zip(model_cls.__columns__.values(), row):
        setattr(obj, column._storage_name, value)
    return obj


def as_dict(obj):
    """orjson `default=` hook: sqlom models aren't stdlib dataclasses, so
    orjson can't introspect them natively."""
    cls = type(obj)
    if hasattr(cls, "__columns__"):
        return {
            name: getattr(obj, column._storage_name)
            for name, column in cls.__columns__.items()
        }
    raise TypeError(f"Cannot serialize {cls!r}")
