from __future__ import annotations

import itertools
import re
import weakref
from contextlib import AbstractAsyncContextManager, asynccontextmanager

from typing import Any, AsyncIterator, Callable, TypeVar

from .compile import (
    ASYNCPG_CONVERTERS,
    compile_batch_hydrator,
    compile_join_hydrator,
)
from .query import Query
from .query import json_bytes as _json_bytes
from .transaction import _ACTIVE, Transaction

R = TypeVar("R")


class AsyncpgTransaction(Transaction):
    """asyncpg: `pool.acquire()` is autocommit, so the BEGIN is explicit."""

    __slots__ = ()
    _placeholder = "$"
    _dialect = "postgres"

    async def _fetch_rows(self, sql, params):
        return await self.connection.fetch(sql, *params)

    async def _fetch_value(self, sql, params):
        return await self.connection.fetchval(sql, *params)

    async def execute(self, sql, *args):
        return await self.connection.execute(sql, *args)

    def transaction(
        self, **kwargs: Any
    ) -> AbstractAsyncContextManager[Transaction]:
        """Nested block. asyncpg turns a nested `transaction()` into a SAVEPOINT."""
        return _asyncpg_block(self._engine, self.connection, self._depth + 1, kwargs)


@asynccontextmanager
async def _asyncpg_block(engine, conn, depth, kwargs):
    tx = AsyncpgTransaction(engine, conn, depth)
    async with conn.transaction(**kwargs):
        tx._enter()
        try:
            yield tx
        finally:
            tx._exit()


class DatabaseEngine:
    """asyncpg-backed engine, as described in the README. Requires a real
    Postgres server; see benchmarks/bench_sqlite.py for a driver-agnostic
    stand-in used to benchmark the hydration path without one.

    **Conditional session reset** (`conditional_reset=True`, the default)

    asyncpg's pool runs `SELECT pg_advisory_unlock_all(); CLOSE ALL; UNLISTEN *;
    RESET ALL;` on every release, as its own server round trip — so a pooled
    request costs two round trips, one of which is cleanup. Measured, that
    cleanup is ~20-30% of throughput (see docs/BENCHMARKS.md §6).

    The usual advice is to pass `reset=` a no-op, but that changes behaviour:
    session state then leaks between requests. This engine takes a third route —
    run the reset only when the connection *could* have been dirtied.

    The invariant that makes it sound: `fetch_all` and `fetch_json` execute only
    SELECT statements generated by `Query`, which compares columns against bound
    parameters. Such a statement cannot leave session state behind — no `SET`, no
    `LISTEN`, no temp table, no server-side cursor, no advisory lock, no open
    transaction. A connection used exclusively through those two methods is
    therefore provably clean and needs no reset.

    Anything else goes through `acquire()`, which marks the connection dirty, so
    the full reset runs on its release.

    Two limits, stated plainly:

    * The guarantee holds only if *all* access goes through this engine. Code
      that reaches into `engine.pool` and runs its own SQL is invisible here.
    * It assumes `Query` keeps emitting plain SELECTs. If the builder ever grows
      raw-SQL fragments or function calls, `SELECT set_config(...)` and
      `SELECT pg_advisory_lock(...)` become reachable and the invariant weakens.

    Note that a custom `reset=` callback does **not** disable asyncpg's own
    protocol-level cleanup: asyncpg still awaits `Connection._reset()` first,
    which rolls back an open transaction and clears client-side listeners. Only
    the SQL reset statement is ours to skip.

    Pass `conditional_reset=False` for asyncpg's unmodified behaviour.
    """

    def __init__(self, dsn: str, *, conditional_reset: bool = True, **pool_kwargs):
        self.dsn = dsn
        self.pool = None
        self.conditional_reset = conditional_reset
        self._pool_kwargs = pool_kwargs
        self._hydrators: dict[Any, Callable[[Any], Any]] = {}
        # Connections needing a SQL reset on release. A WeakSet of the real
        # Connection objects: they are hashable by identity and weakref-able, so
        # this neither keeps closed connections alive nor risks the id() reuse a
        # set of integers would.
        self._dirty: weakref.WeakSet[Any] = weakref.WeakSet()
        self.reset_count = 0

    async def connect(self):
        """Open the pool. Idempotent: a second call reuses the existing pool.

        Without that guard a stray second `connect()` would silently replace the
        pool reference and leak the first one — its connections stay open against
        the server with nothing left holding them.
        """
        if self.pool is not None:
            return self.pool

        import asyncpg

        kwargs = dict(self._pool_kwargs)
        if self.conditional_reset:
            kwargs["reset"] = self._reset_if_dirty
        self.pool = await asyncpg.create_pool(self.dsn, **kwargs)
        return self.pool

    async def close(self):
        """Close the pool and drop the reference, so a later `connect()` opens a
        fresh one by design rather than by overwriting a closed object. Safe to
        call more than once."""
        pool, self.pool = self.pool, None
        if pool is not None:
            await pool.close()
        self._dirty.clear()

    def _require_pool(self):
        if self.pool is None:
            raise RuntimeError(
                "engine is not connected — await engine.connect() first "
                "(or it has been closed)"
            )
        return self.pool

    @staticmethod
    def _real(conn):
        """`pool.acquire()` yields a PoolConnectionProxy while the `reset=` hook
        receives the underlying Connection, so normalise before comparing — the
        two are different objects and mixing them silently defeats the whole
        mechanism."""
        return getattr(conn, "_con", conn)

    async def _reset_if_dirty(self, conn):
        """Pool `reset=` hook: issue the SQL reset only for dirtied connections."""
        real = self._real(conn)
        if real not in self._dirty:
            return
        self._dirty.discard(real)
        reset_query = conn.get_reset_query()
        if reset_query:
            self.reset_count += 1
            await conn.execute(reset_query)

    def _mark_dirty(self, conn):
        self._dirty.add(self._real(conn))

    @asynccontextmanager
    async def acquire(self) -> AsyncIterator[Any]:
        """Raw connection access. Marks the connection dirty, so it gets the
        full session reset on release — use this for anything that is not a
        `Query`, including transactions, `SET`, `LISTEN` and DDL."""
        async with self._require_pool().acquire() as conn:
            self._mark_dirty(conn)
            yield conn

    @asynccontextmanager
    async def transaction(
        self, *, isolation: str | None = None, readonly: bool = False,
        deferrable: bool = False,
    ) -> AsyncIterator[AsyncpgTransaction]:
        """Several statements on one connection, committed together.

        Commits on clean exit, rolls back on any exception. Yields a
        `Transaction` whose `fetch_all`/`fetch_json` take the same `Query`
        objects and reuse the same compiled hydrators as the engine.

        `isolation` accepts asyncpg's names: "read_committed",
        "repeatable_read", "serializable". `deferrable` only applies to a
        serializable read-only transaction.

        Goes through `acquire()`, so the connection is marked dirty and pays the
        full session reset on release — a transaction body can leave session
        state behind, which is exactly what the conditional-reset invariant
        assumes `fetch_all` never does. See sqlom/transaction.py.
        """
        kwargs: dict[str, Any] = {"readonly": readonly, "deferrable": deferrable}
        if isolation is not None:
            kwargs["isolation"] = isolation
        async with self.acquire() as conn:
            async with _asyncpg_block(self, conn, 0, kwargs) as tx:
                yield tx

    def _hydrator_for(self, query):
        """Compiled once per query *shape*, then reused for every row of every
        request. The key is the model class itself for a plain single-model
        select, so this stays the same single dict lookup it always was; joined
        and multi-entity selects key on a tuple describing their entities."""
        key = query._hydration_key
        hydrator = self._hydrators.get(key)
        if hydrator is None:
            # Dispatch on the key's own shape rather than on a second predicate:
            # a plain model key means the fast single-model hydrator, a tuple key
            # means the general one. Deciding this two different ways is how a
            # RIGHT-joined single-entity query once got the fast hydrator and
            # returned an object with every field None.
            if isinstance(key, tuple):
                hydrator = compile_join_hydrator(
                    query.hydration_spec(), ASYNCPG_CONVERTERS, wrap=query.is_multi_entity
                )
            else:
                hydrator = compile_batch_hydrator(query.model, ASYNCPG_CONVERTERS)
            self._hydrators[key] = hydrator
        return hydrator

    @staticmethod
    def _number_placeholders(sql):
        """Deprecated: `to_sql(placeholder="$")` now numbers placeholders itself.

        Kept because the benchmarks call it; it is a no-op for already-numbered
        SQL and only rewrites bare "$" for callers still passing old output.
        """
        if "$1" in sql or "$" not in sql:
            return sql
        counter = itertools.count(1)
        return re.sub(r"\$", lambda _: f"${next(counter)}", sql)

    def _reject_if_in_transaction(self, method):
        """Inside `self.transaction()` this method would take a *different*
        pooled connection, so it would not see the transaction's uncommitted
        writes and would not roll back with it. Fail loudly instead."""
        active = _ACTIVE.get()
        if active is not None and active._engine is self:
            raise RuntimeError(
                f"engine.{method}() was called inside engine.transaction(); it would "
                f"run on a different pooled connection and miss the transaction's "
                f"uncommitted state. Use tx.{method}() instead."
            )

    async def fetch_all(self, query: Query[R]) -> list[R]:
        self._reject_if_in_transaction("fetch_all")
        sql, params = query.to_sql(placeholder="$")
        async with self._require_pool().acquire() as conn:
            rows = await conn.fetch(sql, *params)
        return self._hydrator_for(query)(rows)

    async def fetch_json(self, query: Query[Any]) -> bytes:
        """Return the result set as JSON bytes built by Postgres itself.

        No per-row Python objects are created — the database does the row
        shaping and JSON encoding, and the result goes straight into a
        response body.
        """
        self._reject_if_in_transaction("fetch_json")
        sql, params = query.to_json_sql(dialect="postgres")
        async with self._require_pool().acquire() as conn:
            payload = await conn.fetchval(sql, *params)
        return _json_bytes(payload)
