"""Render the published result tables from recorded runs.

    python scripts/publish_tables.py benchmarks/results/runs/*/run.json

The tables in `docs/METHODOLOGY.md` and `README.md` are generated by this rather
than typed, because they are the numbers the project is judged on and a
transcription slip in one cell is invisible. Point it at the `run.json` files a
`bench micro run --record` sweep wrote and paste what it prints.

**Which metrics, and why those.** Each run carries per-trial `median_ms` and the
harness's own `ratios[]`, so three numbers are available per cell and all three
are printed:

* the **median of the per-trial medians** — the central value;
* **spread%**, `(max - min) / median` across trials, which is the reproducibility
  figure `Cell.summarize` computes and the only thing here that says whether a
  number would come back;
* the **ratio against rowform**, taken from `ratio_with_spread` so it arrives with
  the worst-case interval the trials allow and a `tie` flag. A ratio whose
  interval spans 1.0, or whose medians are within 5%, prints as `~1.0x` rather
  than as a result — METHODOLOGY.md's "group ties instead of ranking them",
  applied mechanically instead of by eye.

Runs that are not `quotable` are still rendered, with the reason, because
refusing to print them would just mean transcribing them by hand instead.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

SHAPES = ("flat", "join", "wide")
BACKENDS = ("sqlite", "postgres", "mock")

#: Row order for the published tables. Contenders absent from a backend/shape
#: render as an em dash. Fixed here rather than taken from the registry so the
#: floors stay above the thing they bound and rowform's three rows stay adjacent.
ROW_ORDER = (
    "raw aiosqlite + dict",
    "raw asyncpg + dict",
    "raw aiosqlite + rowform hydrator",
    "rowform",
    "rowform compat (.scalars())",
    "rowform compat (.all())",
    "rowform (mock)",
    "SQLAlchemy Core (positional)",
    "SQLAlchemy Core (positional) (mock)",
    "SQLAlchemy Core (.mappings())",
    "SQLAlchemy ORM",
    "SQLAlchemy ORM (mock)",
    "SQLAlchemy ORM (DC)",
)

#: How the contender names are spelled in prose, where the registry's names are
#: either too terse or carry a backend suffix the table's own heading supplies.
LABELS = {
    "raw aiosqlite + dict": "raw driver → dicts *(floor)*",
    "raw asyncpg + dict": "raw driver → dicts *(floor)*",
    "raw aiosqlite + rowform hydrator": "raw driver + the same hydrator *(floor)*",
    "rowform": "**rowform** `fetch_all()`",
    "rowform compat (.scalars())": "rowform `execute().scalars()`",
    "rowform compat (.all())": "rowform `execute().all()`",
    "rowform (mock)": "**rowform**",
    "SQLAlchemy Core (positional)": "SQLAlchemy Core (positional)",
    "SQLAlchemy Core (positional) (mock)": "SQLAlchemy Core (positional)",
    "SQLAlchemy Core (.mappings())": "SQLAlchemy Core (`.mappings()`)",
    "SQLAlchemy ORM": "SQLAlchemy ORM",
    "SQLAlchemy ORM (mock)": "SQLAlchemy ORM",
    "SQLAlchemy ORM (DC)": "SQLAlchemy ORM (`MappedAsDataclass`)",
}


def load(paths: list[Path]) -> dict[tuple[str, str], dict[str, Any]]:
    """`(backend, shape) -> {contender: {median, spread_pct, ratio, tie}}`.

    Later runs win, so re-running one cell and re-pointing the glob at both is
    enough to refresh it.
    """
    table: dict[tuple[str, str], dict[str, Any]] = {}
    for path in sorted(paths):
        run = json.loads(path.read_text())
        shape = run["config"]["shape"]
        ratios = {(r["contender"], r["gc"]): r for r in run.get("ratios", [])}
        for cell in run["cells"]:
            backend, gc_mode = cell["params"]["backend"], cell["params"]["gc"]
            summary = cell["summary"]["median_ms"]
            ratio = ratios.get((cell["contender"], gc_mode))
            table.setdefault((backend, shape), {})[cell["contender"]] = {
                "median": summary["median"],
                "spread_pct": summary["spread_pct"],
                "ratio": ratio["value"] if ratio else 1.0,
                "tie": bool(ratio["tie"]) if ratio else False,
                "quotable": run["quotable"],
                "trials": len(cell["trials"]),
            }
    return table


def _cell(entry: dict[str, Any] | None, field: str) -> str:
    if entry is None:
        return "—"
    if field == "median":
        return f"{entry['median']:.4f}"
    if entry["ratio"] == 1.0 and not entry["tie"]:
        return "1.00x"
    return f"~{entry['ratio']:.2f}x" if entry["tie"] else f"{entry['ratio']:.2f}x"


def render(table: dict[tuple[str, str], dict[str, Any]], backend: str, field: str) -> str:
    shapes = [s for s in SHAPES if (backend, s) in table]
    if not shapes:
        return ""
    present = [
        name for name in ROW_ORDER if any(name in table[(backend, s)] for s in shapes)
    ]
    lines = [
        "| contender | " + " | ".join(shapes) + " |",
        "|---|" + "---|" * len(shapes),
    ]
    for name in present:
        cells = [_cell(table[(backend, s)].get(name), field) for s in shapes]
        lines.append(f"| {LABELS.get(name, name)} | " + " | ".join(cells) + " |")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("runs", nargs="+", type=Path)
    args = parser.parse_args()

    table = load(args.runs)
    for backend in BACKENDS:
        if not any(key[0] == backend for key in table):
            continue
        entries = [e for key, cells in table.items() if key[0] == backend for e in cells.values()]
        worst = max(e["spread_pct"] for e in entries)
        trials = sorted({e["trials"] for e in entries})
        print(f"\n### {backend}\n")
        print(render(table, backend, "median"))
        print(f"\n#### {backend} — vs rowform (`~` = tie)\n")
        print(render(table, backend, "ratio"))
        print(
            f"\nworst trial spread across these cells: {worst:.1f}% "
            f"over {trials} trials; quotable="
            f"{sorted({e['quotable'] for e in entries})}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
