"""Render the published result tables from recorded runs.

    python scripts/publish_tables.py benchmarks/results/runs/*/run.json

The tables in `docs/METHODOLOGY.md` and `README.md` are generated by this rather
than typed, because they are the numbers the project is judged on and a
transcription slip in one cell is invisible. Point it at the `run.json` files a
`bench micro run --record` sweep wrote and paste what it prints.

**Which metrics, and why those.** Each run carries per-trial `median_ms` and the
harness's own `ratios[]`, so three numbers are available per cell and all three
are printed:

* the **median of the per-trial medians** — the central value;
* **spread%**, `(max - min) / median` across trials, which is the reproducibility
  figure `Cell.summarize` computes and the only thing here that says whether a
  number would come back;
* the **ratio against rowform**, taken from `ratio_with_spread` so it arrives with
  the worst-case interval the trials allow and a `tie` flag. A ratio whose
  interval spans 1.0, or whose medians are within 5%, prints as `~1.0x` rather
  than as a result — METHODOLOGY.md's "group ties instead of ranking them",
  applied mechanically instead of by eye.

**Columns are `(shape, limit)` pairs, not shapes.** A sweep that records the
same shape at two rows-per-read renders both, because they answer different
questions: at 1000 rows the per-row work dominates and the per-request cost is
~8% of the cell, and at 1 row nothing *but* the per-request cost is left. A table
carrying only the first hides every fixed cost in the stack.

Runs that are not `quotable` are still rendered, with the reason, because
refusing to print them would just mean transcribing them by hand instead.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

SHAPES = ("flat", "join", "wide")
BACKENDS = ("sqlite", "postgres", "postgres-psycopg", "mock")

#: Row order for the published tables. Contenders absent from a backend/shape
#: render as an em dash. Fixed here rather than taken from the registry so the
#: floors stay above the thing they bound and rowform's three rows stay adjacent.
ROW_ORDER = (
    "hand-written dict (mock)",
    "floor: no pool (dict)",
    "floor: hand-rolled (no pool reset)",
    "floor: hand-rolled (dict)",
    "floor: hand-rolled (hydrator)",
    "floor: on SQLAlchemy (dict)",
    "rowform",
    "rowform (prepared)",
    "rowform (idiomatic)",
    "rowform (no transaction)",
    "rowform compat (.scalars())",
    "rowform compat (.all())",
    "rowform (mock)",
    "SQLAlchemy Core (positional)",
    "SQLAlchemy Core (positional, real transaction)",
    "SQLAlchemy Core (positional) (mock)",
    "SQLAlchemy Core (.mappings())",
    "SQLAlchemy ORM",
    "SQLAlchemy ORM (mock)",
    "SQLAlchemy ORM (DC)",
    # The streamed reads, last and as a block: they read the same rows in ten
    # chunks rather than one, so they are comparable with each other and not with
    # the buffered rows above (contenders.py's streaming section).
    "rowform (fetch_iter)",
    "rowform compat (stream())",
    "SQLAlchemy Core (stream())",
)

#: How the contender names are spelled in prose, where the registry's names are
#: either too terse or carry a backend suffix the table's own heading supplies.
LABELS = {
    "hand-written dict (mock)": "hand-written dicts *(parsing floor)*",
    "floor: no pool (dict)": "one dedicated connection → dicts *(floor: no pool)*",
    "floor: hand-rolled (no pool reset)": "raw driver + pool, `reset` off → dicts "
    "*(floor: prices asyncpg's reset)*",
    "floor: hand-rolled (dict)": "raw driver → dicts *(floor: no SQLAlchemy)*",
    "floor: hand-rolled (hydrator)": "raw driver + the same hydrator *(floor: no SQLAlchemy)*",
    "floor: on SQLAlchemy (dict)": "same pool + transaction → dicts *(floor: same plumbing)*",
    "rowform": "**rowform** `fetch_all()` *(equal work)*",
    "rowform (prepared)": "rowform *(prepared, equal payload — prices the cache key)*",
    "rowform (idiomatic)": "rowform *(idiomatic: prepared once, direct to orjson)*",
    "rowform (no transaction)": "rowform `fetch_all()` off the engine *(no transaction)*",
    "rowform compat (.scalars())": "rowform `execute().scalars()`",
    "rowform compat (.all())": "rowform `execute().all()`",
    "rowform (mock)": "rowform",
    "SQLAlchemy Core (positional)": "SQLAlchemy Core (positional)",
    "SQLAlchemy Core (positional, real transaction)": "SQLAlchemy Core (positional) "
    "*(with pysqlite's transaction recipe — prices the guarantee on Core's side)*",
    "SQLAlchemy Core (positional) (mock)": "SQLAlchemy Core (positional)",
    "SQLAlchemy Core (.mappings())": "SQLAlchemy Core (`.mappings()`)",
    "SQLAlchemy ORM": "SQLAlchemy ORM",
    "SQLAlchemy ORM (mock)": "SQLAlchemy ORM",
    "SQLAlchemy ORM (DC)": "SQLAlchemy ORM (`MappedAsDataclass`)",
    "rowform (fetch_iter)": "rowform `fetch_iter()` *(streamed in chunks — the three "
    "streamed rows compare with each other, not with the buffered ones above)*",
    "rowform compat (stream())": "rowform `stream()` *(streamed)*",
    "SQLAlchemy Core (stream())": "SQLAlchemy Core `stream()` *(streamed, in partitions)*",
}

#: Rows whose values are bolded as well as their label — the contender the ratio
#: column is measured against. Emitted here rather than added by hand afterwards,
#: since a hand-edit on the way to the doc is the transcription step this script
#: exists to remove. `rowform (mock)` is deliberately absent: the mock group has
#: no reference — cross-mapper mock ratios compare two seams that exclude
#: different layers, so the harness stopped recording them.
BOLD_ROWS = frozenset({"rowform"})


def load(paths: list[Path], gc: str = "off") -> dict[tuple[str, str, int], dict[str, Any]]:
    """`(backend, shape, limit) -> {contender: {median, spread_pct, ratio, tie}}`.

    Later runs win, so re-running one cell and re-pointing the glob at both is
    enough to refresh it.

    **`limit` is part of the key, not a detail.** Two runs of one shape differing
    only in rows-per-read are different measurements — at 1000 rows the per-row
    work dominates and at 1 row nothing but the per-request cost is left — and
    keyed without it the second would silently overwrite the first.
    """
    table: dict[tuple[str, str, int], dict[str, Any]] = {}
    shas: dict[str, list[str]] = {}
    for path in sorted(paths):
        run = json.loads(path.read_text())
        shape = run["config"]["shape"]
        shas.setdefault(str(run.get("git", {}).get("sha", "unknown")), []).append(path.name)
        recorded = run.get("ratios", [])
        ratios = {(r["contender"], r["gc"]): r for r in recorded}
        # The reference has no ratio of its own — it is what the others are
        # divided by — so it is named on every record instead. Knowing it is what
        # separates "this row is 1.00x by definition" from "nothing was measured
        # here", which look identical from a missing dict entry.
        references = {r["against"] for r in recorded if r["gc"] == gc}
        for cell in run["cells"]:
            if cell["params"]["gc"] != gc:
                continue
            backend = cell["params"]["backend"]
            limit = cell["params"]["limit"]
            summary = cell["summary"]["median_ms"]
            ratio = ratios.get((cell["contender"], gc))
            is_reference = cell["contender"] in references
            table.setdefault((backend, shape, limit), {})[cell["contender"]] = {
                "median": summary["median"],
                "spread_pct": summary["spread_pct"],
                # 1.0 only for the reference itself. None everywhere else means
                # "no ratio was recorded", which is not "this row ties with the
                # reference": a --trials 1 run records no ratios at all (micro.py
                # needs two trials to bound one), and defaulting all of them to
                # 1.0 published a 12x spread as a three-way tie, silently.
                "ratio": ratio["value"] if ratio else (1.0 if is_reference else None),
                "tie": bool(ratio["tie"]) if ratio else False,
                "quotable": run["quotable"],
                "trials": len(cell["trials"]),
                "p95": _worst(cell, "p95_over_p50"),
                "max_over_p50": _worst(cell, "max_over_p50"),
            }
    if not table:
        raise SystemExit(
            f"no cells with gc={gc!r} in those runs — pass --gc to pick a mode "
            f"the sweep actually recorded"
        )
    if len(shas) > 1:
        # "Later runs win" is applied per contender, so re-running one cell and
        # re-globbing over both leaves every other row at the older commit's
        # numbers. One table, one build of the library, or the ratios compare
        # things that never ran against each other.
        detail = "; ".join(f"{sha[:9]}: {', '.join(names)}" for sha, names in sorted(shas.items()))
        raise SystemExit(f"these runs span more than one commit — {detail}")
    return table


def _worst(cell: dict[str, Any], key: str) -> float:
    """The worst trial's value for a detector metric. `Cell.summary` only carries
    the keys the run asked `summarize()` for, so fall back to the trials, which
    always have all of them."""
    summary = cell.get("summary", {}).get(key)
    if summary is not None:
        return summary["max"]
    return max(t["metrics"][key] for t in cell["trials"])


def _cell(entry: dict[str, Any] | None, field: str, *, bold: bool = False) -> str:
    if entry is None:
        return "—"
    if field == "median":
        text = f"{entry['median']:.4f}"
    elif entry["ratio"] is None:
        # No ratio recorded for this cell — a single-trial run, or a reference
        # that was filtered out. Say so; do not render it as a tie.
        return "—"
    elif entry["ratio"] == 1.0 and not entry["tie"]:
        text = "1.00x"
    else:
        text = f"~{entry['ratio']:.2f}x" if entry["tie"] else f"{entry['ratio']:.2f}x"
    return f"**{text}**" if bold else text


def columns(table: dict[tuple[str, str, int], dict[str, Any]], backend: str) -> list[tuple[str, int]]:
    """The `(shape, limit)` pairs recorded for `backend`, in table order.

    Largest limit first, shapes in their usual order within it, so recording a
    small read *appends* a column instead of reordering the table it is being
    added to.
    """
    keys = {(shape, limit) for b, shape, limit in table if b == backend}
    return sorted(keys, key=lambda key: (-key[1], SHAPES.index(key[0])))


def headings(cols: list[tuple[str, int]]) -> list[str]:
    """Bare shape names while one limit is in play — the layout every published
    table has had — and `shape @limit` as soon as two are, because a column of
    1-row reads beside a column of 1000-row reads is unreadable without it."""
    if len({limit for _, limit in cols}) == 1:
        return [shape for shape, _ in cols]
    return [f"{shape} @{limit}" for shape, limit in cols]


def render(table: dict[tuple[str, str, int], dict[str, Any]], backend: str) -> str:
    """One combined table per backend: medians, a blank spacer column, then the
    ratios — the layout that is actually checked into README.md and
    METHODOLOGY.md.

    Emitting the two halves as separate tables (which this did first) meant
    hand-merging them row by row to publish, which is precisely the transcription
    step the script exists to remove.
    """
    cols = columns(table, backend)
    if not cols:
        return ""
    recorded = {name for key in cols for name in table[(backend, *key)]}
    unknown = recorded - set(ROW_ORDER)
    if unknown:
        # Registering a contender and forgetting the constant used to delete it
        # from the published table with no sign it had ever run — the exact
        # silent-omission failure this script exists to prevent.
        raise SystemExit(
            f"{backend}: {', '.join(sorted(unknown))} not in ROW_ORDER, so it "
            f"would be dropped from the table. Add it (and a LABELS entry)."
        )
    present = [name for name in ROW_ORDER if name in recorded]
    span = " | ".join(headings(cols))
    lines = [
        f"| contender | {span} | | {span} |",
        "|---|" + "---|" * (len(cols) * 2 + 1),
    ]
    for name in present:
        entries = [table[(backend, *key)].get(name) for key in cols]
        bold = name in BOLD_ROWS
        medians = " | ".join(_cell(e, "median", bold=bold) for e in entries)
        ratios = " | ".join(_cell(e, "ratio", bold=bold) for e in entries)
        lines.append(f"| {LABELS.get(name, name)} | {medians} | | {ratios} |")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("runs", nargs="+", type=Path)
    parser.add_argument(
        "--gc",
        default="off",
        help="which gc mode's cells to render; a run recorded with --gc both "
        "carries two per contender and only one belongs in a table (default: off)",
    )
    args = parser.parse_args()

    table = load(args.runs, args.gc)
    for backend in BACKENDS:
        if not any(key[0] == backend for key in table):
            continue
        entries = [e for key, cells in table.items() if key[0] == backend for e in cells.values()]
        print(f"\n### {backend}\n")
        print(render(table, backend))
        print(
            f"\nworst across these cells — trial spread "
            f"{max(e['spread_pct'] for e in entries):.1f}%, "
            f"p95/p50 {max(e['p95'] for e in entries):.2f}, "
            f"max/p50 {max(e['max_over_p50'] for e in entries):.2f}; "
            f"trials={sorted({e['trials'] for e in entries})}, "
            f"quotable={sorted({e['quotable'] for e in entries})}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
