"""Render the published result tables from recorded runs.

    python scripts/publish_tables.py benchmarks/results/runs/*/run.json

The tables in `docs/METHODOLOGY.md` and `README.md` are generated by this rather
than typed, because they are the numbers the project is judged on and a
transcription slip in one cell is invisible. Point it at the `run.json` files a
`bench micro run --record` sweep wrote and paste what it prints.

**Which metrics, and why those.** Each run carries per-trial `median_ms` and the
harness's own `ratios[]`, so three numbers are available per cell and all three
are printed:

* the **median of the per-trial medians** — the central value;
* **spread%**, `(max - min) / median` across trials, which is the reproducibility
  figure `Cell.summarize` computes and the only thing here that says whether a
  number would come back;
* the **ratio against rowform**, taken from `ratio_with_spread` so it arrives with
  the worst-case interval the trials allow and a `tie` flag. A ratio whose
  interval spans 1.0, or whose medians are within 5%, prints as `~1.0x` rather
  than as a result — METHODOLOGY.md's "group ties instead of ranking them",
  applied mechanically instead of by eye.

Runs that are not `quotable` are still rendered, with the reason, because
refusing to print them would just mean transcribing them by hand instead.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

SHAPES = ("flat", "join", "wide")
BACKENDS = ("sqlite", "postgres", "mock")

#: Row order for the published tables. Contenders absent from a backend/shape
#: render as an em dash. Fixed here rather than taken from the registry so the
#: floors stay above the thing they bound and rowform's three rows stay adjacent.
ROW_ORDER = (
    "hand-written dict (mock)",
    "floor: hand-rolled (dict)",
    "floor: hand-rolled (hydrator)",
    "floor: on SQLAlchemy (dict)",
    "rowform",
    "rowform (idiomatic)",
    "rowform (no transaction)",
    "rowform compat (.scalars())",
    "rowform compat (.all())",
    "rowform (mock)",
    "SQLAlchemy Core (positional)",
    "SQLAlchemy Core (positional) (mock)",
    "SQLAlchemy Core (.mappings())",
    "SQLAlchemy ORM",
    "SQLAlchemy ORM (mock)",
    "SQLAlchemy ORM (DC)",
)

#: How the contender names are spelled in prose, where the registry's names are
#: either too terse or carry a backend suffix the table's own heading supplies.
LABELS = {
    "hand-written dict (mock)": "hand-written dicts *(parsing floor)*",
    "floor: hand-rolled (dict)": "raw driver → dicts *(floor: no SQLAlchemy)*",
    "floor: hand-rolled (hydrator)": "raw driver + the same hydrator *(floor: no SQLAlchemy)*",
    "floor: on SQLAlchemy (dict)": "same pool + transaction → dicts *(floor: same plumbing)*",
    "rowform": "**rowform** `fetch_all()` *(equal work)*",
    "rowform (idiomatic)": "rowform *(idiomatic: prepared once, direct to orjson)*",
    "rowform (no transaction)": "rowform `fetch_all()` off the engine *(no transaction)*",
    "rowform compat (.scalars())": "rowform `execute().scalars()`",
    "rowform compat (.all())": "rowform `execute().all()`",
    "rowform (mock)": "rowform",
    "SQLAlchemy Core (positional)": "SQLAlchemy Core (positional)",
    "SQLAlchemy Core (positional) (mock)": "SQLAlchemy Core (positional)",
    "SQLAlchemy Core (.mappings())": "SQLAlchemy Core (`.mappings()`)",
    "SQLAlchemy ORM": "SQLAlchemy ORM",
    "SQLAlchemy ORM (mock)": "SQLAlchemy ORM",
    "SQLAlchemy ORM (DC)": "SQLAlchemy ORM (`MappedAsDataclass`)",
}

#: Rows whose values are bolded as well as their label — the contender the ratio
#: column is measured against. Emitted here rather than added by hand afterwards,
#: since a hand-edit on the way to the doc is the transcription step this script
#: exists to remove. `rowform (mock)` is deliberately absent: the mock group has
#: no reference — cross-mapper mock ratios compare two seams that exclude
#: different layers, so the harness stopped recording them.
BOLD_ROWS = frozenset({"rowform"})


def load(paths: list[Path], gc: str = "off") -> dict[tuple[str, str], dict[str, Any]]:
    """`(backend, shape) -> {contender: {median, spread_pct, ratio, tie}}`.

    Later runs win, so re-running one cell and re-pointing the glob at both is
    enough to refresh it.
    """
    table: dict[tuple[str, str], dict[str, Any]] = {}
    shas: dict[str, list[str]] = {}
    for path in sorted(paths):
        run = json.loads(path.read_text())
        shape = run["config"]["shape"]
        shas.setdefault(str(run.get("git", {}).get("sha", "unknown")), []).append(path.name)
        recorded = run.get("ratios", [])
        ratios = {(r["contender"], r["gc"]): r for r in recorded}
        # The reference has no ratio of its own — it is what the others are
        # divided by — so it is named on every record instead. Knowing it is what
        # separates "this row is 1.00x by definition" from "nothing was measured
        # here", which look identical from a missing dict entry.
        references = {r["against"] for r in recorded if r["gc"] == gc}
        for cell in run["cells"]:
            if cell["params"]["gc"] != gc:
                continue
            backend = cell["params"]["backend"]
            summary = cell["summary"]["median_ms"]
            ratio = ratios.get((cell["contender"], gc))
            is_reference = cell["contender"] in references
            table.setdefault((backend, shape), {})[cell["contender"]] = {
                "median": summary["median"],
                "spread_pct": summary["spread_pct"],
                # 1.0 only for the reference itself. None everywhere else means
                # "no ratio was recorded", which is not "this row ties with the
                # reference": a --trials 1 run records no ratios at all (micro.py
                # needs two trials to bound one), and defaulting all of them to
                # 1.0 published a 12x spread as a three-way tie, silently.
                "ratio": ratio["value"] if ratio else (1.0 if is_reference else None),
                "tie": bool(ratio["tie"]) if ratio else False,
                "quotable": run["quotable"],
                "trials": len(cell["trials"]),
                "p95": _worst(cell, "p95_over_p50"),
                "max_over_p50": _worst(cell, "max_over_p50"),
            }
    if not table:
        raise SystemExit(
            f"no cells with gc={gc!r} in those runs — pass --gc to pick a mode "
            f"the sweep actually recorded"
        )
    if len(shas) > 1:
        # "Later runs win" is applied per contender, so re-running one cell and
        # re-globbing over both leaves every other row at the older commit's
        # numbers. One table, one build of the library, or the ratios compare
        # things that never ran against each other.
        detail = "; ".join(f"{sha[:9]}: {', '.join(names)}" for sha, names in sorted(shas.items()))
        raise SystemExit(f"these runs span more than one commit — {detail}")
    return table


def _worst(cell: dict[str, Any], key: str) -> float:
    """The worst trial's value for a detector metric. `Cell.summary` only carries
    the keys the run asked `summarize()` for, so fall back to the trials, which
    always have all of them."""
    summary = cell.get("summary", {}).get(key)
    if summary is not None:
        return summary["max"]
    return max(t["metrics"][key] for t in cell["trials"])


def _cell(entry: dict[str, Any] | None, field: str, *, bold: bool = False) -> str:
    if entry is None:
        return "—"
    if field == "median":
        text = f"{entry['median']:.4f}"
    elif entry["ratio"] is None:
        # No ratio recorded for this cell — a single-trial run, or a reference
        # that was filtered out. Say so; do not render it as a tie.
        return "—"
    elif entry["ratio"] == 1.0 and not entry["tie"]:
        text = "1.00x"
    else:
        text = f"~{entry['ratio']:.2f}x" if entry["tie"] else f"{entry['ratio']:.2f}x"
    return f"**{text}**" if bold else text


def render(table: dict[tuple[str, str], dict[str, Any]], backend: str) -> str:
    """One combined table per backend: medians, a blank spacer column, then the
    ratios — the layout that is actually checked into README.md and
    METHODOLOGY.md.

    Emitting the two halves as separate tables (which this did first) meant
    hand-merging them row by row to publish, which is precisely the transcription
    step the script exists to remove.
    """
    shapes = [s for s in SHAPES if (backend, s) in table]
    if not shapes:
        return ""
    recorded = {name for s in shapes for name in table[(backend, s)]}
    unknown = recorded - set(ROW_ORDER)
    if unknown:
        # Registering a contender and forgetting the constant used to delete it
        # from the published table with no sign it had ever run — the exact
        # silent-omission failure this script exists to prevent.
        raise SystemExit(
            f"{backend}: {', '.join(sorted(unknown))} not in ROW_ORDER, so it "
            f"would be dropped from the table. Add it (and a LABELS entry)."
        )
    present = [name for name in ROW_ORDER if name in recorded]
    span = " | ".join(shapes)
    lines = [
        f"| contender | {span} | | {span} |",
        "|---|" + "---|" * (len(shapes) * 2 + 1),
    ]
    for name in present:
        entries = [table[(backend, s)].get(name) for s in shapes]
        bold = name in BOLD_ROWS
        medians = " | ".join(_cell(e, "median", bold=bold) for e in entries)
        ratios = " | ".join(_cell(e, "ratio", bold=bold) for e in entries)
        lines.append(f"| {LABELS.get(name, name)} | {medians} | | {ratios} |")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("runs", nargs="+", type=Path)
    parser.add_argument(
        "--gc",
        default="off",
        help="which gc mode's cells to render; a run recorded with --gc both "
        "carries two per contender and only one belongs in a table (default: off)",
    )
    args = parser.parse_args()

    table = load(args.runs, args.gc)
    for backend in BACKENDS:
        if not any(key[0] == backend for key in table):
            continue
        entries = [e for key, cells in table.items() if key[0] == backend for e in cells.values()]
        print(f"\n### {backend}\n")
        print(render(table, backend))
        print(
            f"\nworst across these cells — trial spread "
            f"{max(e['spread_pct'] for e in entries):.1f}%, "
            f"p95/p50 {max(e['p95'] for e in entries):.2f}, "
            f"max/p50 {max(e['max_over_p50'] for e in entries):.2f}; "
            f"trials={sorted({e['trials'] for e in entries})}, "
            f"quotable={sorted({e['quotable'] for e in entries})}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
